### Sign in and get token
POST https://vtfmhkpfmavhkyhmjpty.supabase.co/auth/v1/token?grant_type=password
Content-Type: application/json
apikey: sb_publishable_VDbPxDBDeIBrXtpkLuX9gQ_s5vFbjou

{
    "email": "reuben.farrel27@gmail.com",
    "password": "12345"
}

 "access_token": "eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg",
  "token_type": "bearer",

### Get my profile
GET http://localhost:8000/profiles/me
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg

### Update my profile
PATCH http://localhost:8000/profiles/me
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg
Content-Type: application/json

{
    "preferred_name": "Ben",
    "timezone": "Asia/Singapore"
}

### Create a medication
POST http://localhost:8000/medications/
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg
Content-Type: application/json

{
    "name": "Metformin",
    "dosage_amount": 500,
    "dosage_unit": "mg",
    "form": "tablet",
    "instructions": "Take after meals",
    "start_date": "2024-01-01"
}

### Get all medications
GET http://localhost:8000/medications/
Authorization:  Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg

### Create a schedule (replace medication-id with the id returned above)
POST http://localhost:8000/medications/6f15b34a-2471-41a7-82a9-ffae745913dc/schedules
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg
Content-Type: application/json

{
    "schedule_type": "daily",
    "times_per_day": 2,
    "time_slots": ["08:00", "20:00"],
    "days_of_week": [1,2,3,4,5,6,7]
}

### Get today's logs
GET http://localhost:8000/medications/logs/today
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg

### Mark a dose as taken (replace log-id with id from today's logs)
PATCH http://localhost:8000/medications/logs/e50094b9-4431-4cb8-a1ab-1a9a597a00fc
Authorization:  Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImUxNjdiYzZjLWY5MjAtNDYzNC1hYTZmLTg2N2M4NTVmZWMxNSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3Z0Zm1oa3BmbWF2aGt5aG1qcHR5LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlNzIzNmYwOS02YzZhLTQ1NWEtYjc0ZS04NzY1N2M4NTEyZjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc0NjcxNTcxLCJpYXQiOjE3NzQ2Njc5NzEsImVtYWlsIjoicmV1YmVuLmZhcnJlbDI3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzc0NjY3OTcxfV0sInNlc3Npb25faWQiOiI1NjYwM2M1NC1kY2M1LTQyMDAtYjgxNy1hMTdkODdjMzVhNTMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.oX4WTXFPAbgjOzuzM-KCsa7-ZuZOPXW22z0q5vnoCAmLU0nt0PkYFeaZfiNGdIk9Mkutvg8l_If1KwmEJ1Mmfg
Content-Type: application/json

{
    "status": "taken"
}